export const reviewPlaceholders = {
  6: [
    'I really liked this because...',
    'This part stands out because...',
    'This is effective because...',
    'This works well because...',
    'This aspect is really strong because...',
    'This is a great example of...',
    'I’m impressed by...',
    'This is impressive because...',
    'This is well-done because...',
    'This part is particularly strong because...',
    'This is a good example of...',
    'I appreciate how this...',
    'This is noteworthy because...',
    'I think this enhances...',
    'This might be more beneficial if...',
    'I think this demonstrates...',
    'This highlights...',
    'This supports...',
    'This clarifies...',
    'I think this improves...',
  ],
  5: [
    'This is beneficial because...',
    'This is well-aligned because...',
    'This could be more effective if...',
    'I think this aligns well with...',
    'This might be better suited for...',
    'This could be more user-friendly by...',
    'This works well because...',
    'This part seems well-implemented because...',
    'This aspect is strong because...',
    'I think this is well-executed because...',
    'This is a good practice because...',
    'This might be more efficient by...',
    'This is useful because...',
    'This could be more robust if...',
    'This is a well-considered approach because...',
    'I think it’s advantageous to...',
    'This might be more straightforward if...',
    'This should be more comprehensive because...',
    'This could be more user-centric by...',
    'It’s beneficial because...',
  ],
  4: [
    'My opinion about this is...',
    'I think this could be improved by...',
    'One thing I noticed is...',
    'I found this confusing because...',
    'This could be more efficient by...',
    'I suggest reviewing...',
    'This might be problematic because...',
    'One improvement could be...',
    'This could be clearer if...',
    'I noticed that...',
    'This could be simplified by...',
    'I think it’s important to...',
    'This could be more consistent with...',
    'I propose changing...',
    'This might need adjustment because...',
    'This could be less complex if...',
    'I suggest refining...',
    'It’s worth noting that...',
    'This could be more readable by...',
    'I recommend adjusting...',
  ],
  3: [
    'This needs more explanation about...',
    'I believe this should...',
    'This could cause problems if...',
    'Consider adding more details about...',
    'This could be optimized by...',
    'It would be helpful if...',
    'A better way to do this might be...',
    'This might be too complex because...',
    'This seems redundant because...',
    'This section could benefit from...',
    'This could be clearer with...',
    'I suggest rethinking...',
    'This might be confusing because...',
    'This needs further testing because...',
    'This should be reconsidered because...',
    'This might need reconsideration because...',
    'This could be more flexible by...',
    'This might be more reliable if...',
    'This could be more descriptive by...',
    'This might conflict with...',
  ],
  2: [
    'A potential issue here is...',
    'I have concerns about...',
    'This could be a potential risk because...',
    'This might be problematic because...',
    'This could be risky because...',
    'This could pose a challenge if...',
    'This needs reevaluation because...',
    'This could be more precise by...',
    'This might be more balanced if...',
    'I suggest investigating...',
    'This could be problematic in terms of...',
    'This needs more alignment with...',
    'This might be more efficient with...',
    'This could be more adaptable by...',
    'This might be more consistent by...',
    'This needs clarification about...',
    'This might be more beneficial if...',
    'This should be more robust because...',
    'This might need simplification because...',
    'This needs to be more specific about...',
  ],
  1: [
    'This is confusing because...',
    'This could cause issues because...',
    'This seems redundant because...',
    'This might be problematic in terms of...',
    'This might be too complex because...',
    'This might need adjustment because...',
    'This could pose a risk if...',
    'This might conflict with other parts...',
    'This might need reconsideration because...',
    'This could be problematic because...',
    'This needs to be more specific about...',
    'This might be confusing if...',
    'This needs reevaluation because...',
    'This might be problematic in terms of...',
    'This might need simplification because...',
    'This might need further testing because...',
    'This could be risky because...',
    'This needs more alignment with...',
    'This might need adjustment because...',
    'This might be too complex because...',
  ],
  0: [
    'This part is not applicable because...',
    "This doesn't seem relevant because...",
    'This section might not apply due to...',
    'This might be unnecessary because...',
    'This aspect might not be relevant because...',
    "This doesn't appear to be necessary because...",
    'This might not be required because...',
    "This part doesn't seem applicable because...",
    'This could be excluded because...',
    "This section doesn't apply in this context...",
    "This doesn't seem pertinent because...",
    'This part might be irrelevant due to...',
    'This might not be needed because...',
    "This doesn't seem to fit because...",
    "This doesn't seem to belong because...",
    'This might not be relevant here because...',
    "This part doesn't appear necessary because...",
    'This might be nonessential because...',
    'This section might be redundant because...',
    "This doesn't seem necessary in this context...",
  ],
};
